var anchoviesPizzaScore = 0;
var pepperoniPizzaScore = 4;
var hawaiianPizzaScore = 4;
var chickenBaconPizzaScore = 6;
console.log(anchoviesPizzaScore < pepperoniPizzaScore); //True
console.log(chickenBaconPizzaScore > hawaiianPizzaScore); //True
console.log(hawaiianPizzaScore > pepperoniPizzaScore); //false
console.log(pepperoniPizzaScore <= chickenBaconPizzaScore); //True
console.log(hawaiianPizzaScore >= pepperoniPizzaScore) //True
